name: Build and Publish
on: [push]

jobs:
  build:
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/jhuntoo/terraform-provider-gitlab

      - name: Build
        uses: cedrickring/golang-action@1.3.0
        with:
          args: make build
        env:
          GOPATH: /home/runner/work/jhuntoo/terraform-provider-gitlab 
          IMPORT: "jhuntoo/terraform-provider-gitlab"
          GOFLAGS: -mod=vendor
          GO111MODULE: on
      - name: Debug
        run: |
          pwd
          echo ${HOME}
          echo ${GITHUB_WORKSPACE}
          echo ${GOPATH}
          echo ${GOROOT}
        env:
          GOPATH: /home/runner/work/jhuntoo/terraform-provider-gitlab  

          
      - name: Create Release
        uses: docker://softprops/action-gh-release
        with:
          files: /home/runner/work/jhuntoo/terraform-provider-gitlab/bin/terraform-provider-gitlab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}