name: Build and Publish
on: [push]

jobs:
  build:
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run custom command
        uses: cedrickring/golang-action@1.3.0
        with:
          args: make build
        env:
          IMPORT: "jhuntoo/terraform-provider-gitlab"